services:
  - type: web
    name: fakers-the-imposter-game
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_KEY
        value: sb_publishable_ZBfL7g6kEPj3vvEHvmns9g_Cuzw7N-V
      - key: SUPABASE_URL
        value: https://zbfl7g6kepj3vvehvmns.supabase.co
